# -*- coding: utf-8 -*-
"""QuantumCircuit2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a_J3l_Xmua6OjjCKOUwEI8XMfQi4E78P
"""

!pip install qiskit[visualization]==0.43.3

!pip install qiskit-aer

from qiskit import ClassicalRegister, QuantumRegister, QuantumCircuit, execute
from qiskit import Aer

q2 = QuantumRegister(4, "Qreg")

c2 = ClassicalRegister(4, "Creg")

qc2 = QuantumCircuit(q2, c2)

qc2.x(q2[0])
qc2.x(q2[0])

qc2.x(q2[3])

qc2.x(q2[2])
qc2.x(q2[2])
qc2.x(q2[2])

qc2.x(q2[1])
qc2.x(q2[1])
qc2.x(q2[1])
qc2.x(q2[1])

qc2.barrier()

qc2.measure(q2, c2)

qc2.draw(output='mpl')